import os

from dotenv import load_dotenv

load_dotenv()

AGENT_STATUS_CHECK_TIMEOUT_SECONDS = float(
    os.getenv('AGENT_STATUS_CHECK_TIMEOUT_SECONDS', '12')
)
AGENT_STATUS_CACHE_TTL_SECONDS = int(os.getenv('AGENT_STATUS_CACHE_TTL_SECONDS', '30'))
SECRET_KEY = os.getenv('SECRET_KEY', 'change-me-in-production')
JWT_ALGORITHM = os.getenv('JWT_ALGORITHM', 'HS256')
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv('ACCESS_TOKEN_EXPIRE_MINUTES', '120'))
REFRESH_TOKEN_EXPIRE_DAYS = int(os.getenv('REFRESH_TOKEN_EXPIRE_DAYS', '30'))
STREAM_CONNECT_TIMEOUT_SECONDS = float(os.getenv('STREAM_CONNECT_TIMEOUT_SECONDS', '60'))
STREAM_READ_TIMEOUT_SECONDS = float(os.getenv('STREAM_READ_TIMEOUT_SECONDS', '240'))
